# This is a basic workflow to help you get started with Actions

name: issues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the src branch
on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Env
      run: env
